#!/usr/bin/env bash

# tmux color setting as default
[ -x "$(command -v tmux)" ] && alias tmux='tmux -2'

# color less
export LESS_TERMCAP_mb=$'\e[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\e[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\e[0m'           # end mode
export LESS_TERMCAP_se=$'\e[39;49m'           # end standout-mode
export LESS_TERMCAP_so=$'\e[30;43m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\e[0m'           # end underline
export LESS_TERMCAP_us=$'\e[04;38;5;146m' # begin underline

