#!/bin/zsh

############################################################################
## Common configuration													#
############################################################################
export PATH_ORG=$PATH
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=-1;32:locus=01:quote=01'

export PATH="$PATH:/usr/local/opt/qt/bin"

# Simple script for network check
[ -x "$(command -v curl)" ] && alias myip='curl ifconfig.co/'

# Enable direnv hook
[ -x "$(command -v direnv)" ] && eval "$(direnv hook zsh)"

# Enable nvm
## Set NVM directory
[ -z "$NVM_DIR" ] && [ -z "${XDG_CONFIG_HOME-}" ] \
	&& export NVM_DIR="$HOME/.nvm"
## Load nvm.sh from available lists
[ -z "$NVM_SH" ] && [ -s "$NVM_DIR/nvm.sh" ] \
	&& export NVM_SH="$NVM_DIR/nvm.sh"
[ -z "$NVM_SH" ] && [ -s "/usr/share/nvm/nvm.sh" ] \
	&& export NVM_SH="/usr/share/nvm/nvm.sh"
[ -z "$NVM_SH" ] && [ -s "/usr/local/opt/nvm/nvm.sh" ] \
	&& export NVM_SH="/usr/local/opt/nvm/nvm.sh"
[ -s "$NVM_SH" ] && source "$NVM_SH" && unset NVM_SH
# Load nvm bash complettion from available lists
[ -z "$NVM_SCPL" ] && [ -s "$NVM_DIR/bash_completion" ] \
	&& export NVM_SCPL="$NVM_DIR/bash_completion"
[ -z "$NVM_SCPL" ] && [ -s "/usr/share/nvm/bash_completion" ] \
	&& export NVM_SCPL="/usr/share/nvm/bash_completion"
[ -z "$NVM_SCPL" ] && [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] \
	&& export NVM_SCPL="/usr/local/opt/nvm/etc/bash_completion.d/nvm"
[ -s "$NVM_SCPL" ] && source "$NVM_SCPL" && unset NVM_SCPL


# change go envvironment
[ -x "$(command -v go)" ] && [ -z "$GOROOT" ] \
	&& export GOROOT="$(go env GOROOT)"
[ -d $GOROOT ] && [ -d "$HOME/Workspace/go" ] \
	&& export GOPATH="$HOME/Workspace/go" && export PATH=$PATH:$GOPATH/bin:$GOROOT/bin

# add environment script sourcing function
export RC_DIR="$HOME/Workspace/.envscripts"

function loadenv() {
	source "$RC_DIR/$1"
}
function _loadenv_complete() {
	local rc_dir=${RC_DIR:-$HOME/.rc}
	local search_dir=${1:-$rc_dir}
	local rc_files=(${(f)"$(find $search_dir -name '*.rc' -o -name '*.sh')"})
	local completions=()

	for file in ${rc_files[@]}; do
		completions+=("${file#$rc_dir/}")
	done

	compadd -U -W "${completions[@]}"
}
compdef _loadenv_complete loadenv

# Reset exit code to 0 for this script
# (Short-circuit condition check & apply may change exit code)
true
